### ISSUE TITLE
V1.0.0-BETA fails to launch

### ISSUE THREAD

**Issue by bullseye555** [dhmay/jamstats#100] opened 2023-02-05 01:53 UTC
**Describe the bug**
Downloaded V1.0.0-BETA from GitHub, and EXE runs but fails to open JamStats

**To Reproduce**
Running on Windows 11 / Windows Server 2019, fails to launch due to error. See screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/28804763/216797548-c6f1a1b4-2cbb-441e-bb00-1dcfd55cd6c2.png)

**Comment by dhmay** [comment] 2023-02-05 02:16
Ugggh, thank you! This was a stupid oversight. I need better tests. Fixing...

**Comment by dhmay** [comment] 2023-02-05 02:21
Fixed, I believe. Can you please give it a go, @bullseye555 ?

I fixed by doctoring the 1.0.0 binary, but I'll also make a 1.0.1 so the code's in sync with the binary for the latest release.

**Comment by bullseye555** [comment] 2023-02-05 02:31
Using the EXE from https://github.com/dhmay/jamstats/actions/runs/4094495792 I get this
![image](https://user-images.githubusercontent.com/28804763/216798403-05a40943-f688-4410-b62f-a9c0204c97d0.png)

Same problem from https://github.com/dhmay/jamstats/actions/runs/4094490903

**Comment by dhmay** [comment] 2023-02-05 02:59
You are the best user I do not deserve you. I believe I've fixed it now, in the 1.0.0 release and also in the new 1.0.2. Please give it a go.

**Comment by bullseye555** [comment] 2023-02-05 03:08
Ok - It launches now, and I can get it running & connected to a game, but if there's no game in progress, I'm getting the following
![image](https://user-images.githubusercontent.com/28804763/216799384-134d6776-ed64-4153-80ea-ff923a77d759.png)

```
Traceback (most recent call last):
  File "flask\app.py", line 2548, in __call__
  File "flask\app.py", line 2528, in wsgi_app
  File "flask\app.py", line 2525, in wsgi_app
  File "flask\app.py", line 1822, in full_dispatch_request
  File "flask\app.py", line 1820, in full_dispatch_request
  File "flask\app.py", line 1796, in dispatch_request
  File "jamstats\web\statserver.py", line 141, in index
  File "jamstats\data\json_to_pandas.py", line 39, in load_json_derby_game
  File "jamstats\data\json_to_pandas.py", line 413, in extract_roster
  File "pandas\core\generic.py", line 5487, in __getattr__
AttributeError: 'DataFrame' object has no attribute 'Id'
```

I'm heading off to training now, so any changes I'll have a look at there if I've got nothing else to do, or when I get home

**Comment by bullseye555** [comment] 2023-02-05 03:11
Confirmed also fails in 1.0.2

Also

> You are the best user I do not deserve you
Every user should be like me :P

**Comment by dhmay** [comment] 2023-02-05 06:05
Whew, ok. At least the really tragic stuff is fixed.

What did it do *before* when you tried to connect to a server with no running game? What do you think is proper behavior... show some error message and keep refreshing and trying again?

**Comment by dhmay** [comment] 2023-02-05 06:34
What exactly do you do to put the scoreboard in a state where there's no game in progress? Sorry, for someone who gets data from the scoreboard I have remarkably little idea how to work it.

Give this executable a go and see if it seems reasonable to you... I tried to make it show an error message if you end up in that state.

I bet if you have it connected to a game, then you end that game, then you start another, it'll get *really* confused.
https://github.com/dhmay/jamstats/suites/10785298288/artifacts/542130754

**Comment by bullseye555** [comment] 2023-02-05 21:28
> Whew, ok. At least the really tragic stuff is fixed.
LOL!!!

> What did it do before when you tried to connect to a server with no running game? What do you think is proper behavior... show some error message and keep refreshing and trying again?
See #91 and #92 

> What exactly do you do to put the scoreboard in a state where there's no game in progress? Sorry, for someone who gets data from the scoreboard I have remarkably little idea how to work it.

(Assuming a fresh download of CRG that has never been opened before - or everything in the **\config\autosave** subfolder is deleted)
Easiest way to do this is to just start CRG (_scoreboard.sh_ or _scoreboard-Windows.exe_ depending on your OS, which I'm assuming from past notes is a Mac) and then connect to it with JamStats

(I'll give some REALLLLLY basic SBO stuff below)
To start a game:
1. goto localhost:8000
2. click on _Scoreboard Operator Panel_
![image](https://user-images.githubusercontent.com/28804763/216846269-1f6225f1-0a55-4413-9633-3058ceffaec3.png)
4. Click the x at Operator Login (or you can put a name in - doesn't matter for what we're doing here)
![image](https://user-images.githubusercontent.com/28804763/216846298-5eb27a67-e546-4683-934c-f1fa58690f9e.png)
6. Use the _Start Jam_ etc buttons along the top to control if a Jam is in progress (these are dynamic, so will change depending on the state of the game clocks)
![image](https://user-images.githubusercontent.com/28804763/216846399-f1c81d18-198d-49f4-a9ad-4527085d9f8d.png)

To start a New Game (and simulate the change of games in a multigame tournament [ this assumes you haven't spent an hour simulating a game and just want to cut the existing game short)
1. Probably easier to just show you - let me know if none of this makes sense :)
https://user-images.githubusercontent.com/28804763/216846754-6b58bc5b-bf6e-4d24-a14e-c9252a3e02dd.mp4

> Give this executable a go and see if it seems reasonable to you... I tried to make it show an error message if you end up in that state. It should autorefresh until it can connect.
I get this when game has not yet started (fresh game)
![image](https://user-images.githubusercontent.com/28804763/216846858-d27d1477-1809-43da-86f2-69a385d3b774.png)
But it doesn't (appear to) auto-refresh to re-connect, and when forced refresh and the game is in progress, it doesn't change to the in-progress game
![image](https://user-images.githubusercontent.com/28804763/216846990-21c2a9b7-6fe0-481e-b26a-25964dbc4e97.png)


It would be better, if possible, to go back to the original handling? Or if not, maybe update the wording to say _No game currently in progress - Retrying in x_ [where x is a countdown timer to autorefresh?]

**Comment by dhmay** [comment] 2023-02-05 23:15
Thanks! I'll work on this this week. At least this is all stuff I can test out on my Mac.

**Comment by dhmay** [comment] 2023-02-11 20:34
OK, I think the behavior should be better now. I made it so that, if a) jamstats hasn't successfully connected to the server, or b) it has lost the connection (e.g., server shuts down), it will start over from the beginning and try to connect, on refresh. Refreshes seem to be happening as they should. Let me know how it goes!

**Comment by dhmay** [comment] 2023-02-11 20:35
You can download the fix here when the build completes:
https://github.com/dhmay/jamstats/actions/runs/4153047363

**Comment by bullseye555** [comment] 2023-02-11 23:41
It starts now, yay! 

But if there game finishes, and I start a _new_ game, it goes to the Error message, but never picks up the start of the game
![image](https://user-images.githubusercontent.com/28804763/218285650-19c548c0-279c-4c9e-94e8-5659033870cc.png)

**Comment by dhmay** [comment] 2023-02-12 17:57
OK, I can reproduce that problem. I think what's happening is, when the scoreboard starts a new game, it sends out a bunch of game data that is getting added to the existing game data from the finished game. Jamstats tries to treat it all as a single coherent game and fails.

To fix it, I'm going to have to learn more about what the scoreboard sends out when it starts a new game. Then, when I get that message, I can clear out the old game data and start over.

**Comment by dhmay** [comment] 2023-02-12 18:16
@frank-weinberg With the websocket interface, is there some way for me to tell that a new game has started? Currently, I'm only subscribing to `ScoreBoard.Version(release)` and `ScoreBoard.CurrentGame`. Is there a message outside of those two scopes that gets sent when a new game starts? Sorry if this is documented somewhere on the wiki, I couldn't find it there.

If there's no signal I can rely on that a new game has started, I'm thinking I can just check for something within the CurrentGame scope that would suggest that a new game has started, as an indication that I should dump all current state and start over. Does that make sense? Do you have a suggestion for which tag to look for?

**Comment by frank-weinberg** [comment] 2023-02-12 18:27
@dhmay `ScoreBoard.CurrentGame.Game` changes when a new game is started.

But you shouldn't have to rely on this, as all values from the old game should be overwritten by either a value from the new game or `null`. If jamstats doesn't pick those updates up properly, there are likely to be more bugs lingering, as data being set to `null` also happens during a game.

**Comment by frank-weinberg** [comment] 2023-02-12 18:32
Thinking about it some more, what may be happening is that an update like `ScoreBoard.CurrentGame.Period(1): null` does not lead toe all values starting with `ScoreBoard.CurrentGame.Period(1).` being deleted as you maybe only look for full matches.

**Comment by dhmay** [comment] 2023-02-12 18:41
Yep, I'm pretty sure that's part of my problem. I'm definitely only matching full keys.

Do you think that's going to cause more problems than just new-game problems? I think I can deal with the new-game issue by looking for `ScoreBoard.CurrentGame.Game`, but I don't want my game state to be getting out of whack in other ways throughout a game.

(you can see why I initially used the JSON interface! :D )

**Comment by frank-weinberg** [comment] 2023-02-12 18:48
That can definitely happen in a game. Situations that immediately come to mind:
- deleting a Jam
- deleting a Penalty

There are probably more.

**Comment by dhmay** [comment] 2023-02-12 18:57
Is there a general approach to loose-matching on key names that I should use to make sure my game state reflects what the server is trying to tell me?

Could I do something like: if I receive a particular JSON key, remove all keys that start with that key? Like, receiving:

`ScoreBoard.CurrentGame.Period(1).`

would remove

`ScoreBoard.CurrentGame.Period(1).blahblah`
and
`ScoreBoard.CurrentGame.Period(1).blahblahblah`

?

**Comment by dhmay** [comment] 2023-02-12 19:10
OK, @bullseye555 , I think I've got jamstats picking up a new game when the server starts a new game. Let me know how it's looking to you. New build artifact:
https://github.com/dhmay/jamstats/actions/runs/4157823575

**Comment by frank-weinberg** [comment] 2023-02-12 19:10
A key being set to `null` should delete
- an exact match
- anything that starts with the key followed by a `.` (Keys sent will not end with a `.`)

**Comment by dhmay** [comment] 2023-02-12 23:11
Thanks, @frank-weinberg! I've added the proper data deletion to jamstats.

**Comment by dhmay** [comment] 2023-02-12 23:12
@bullseye555 , if you want to test out deleting a jam or a penalty, along with jamstats properly picking up a new game, grab the build artifact here:
https://github.com/dhmay/jamstats/actions/runs/4158693537

**Comment by bullseye555** [comment] 2023-02-13 00:20
@dhmay - using the second artifact, I have good new & bad news
>Good news

Connecting to scoreboard before the game starts shows the _Error Connecting_ message, and then when the game starts, it correctly updates to the view showing data
Deleting a penalty correctly removes it from the counts (I hadn't even thought of validating deleting things!!)

>Bad News

1. When a game finishes and a new game is created, it correctly goes to the _Error Connecting_ message. **But** once the new game has started, it doesn't pickup the new game and remains at the _Error Connecting_ page
2. When _Unstarting_ a Jam (eg: Making it so that the Jam that was just started was undone and never occurred) or _deleting_ a Jam (eg: start jam, stop jam, delete that jam) it goes to the _Error Connecting_ page, but once the next Jam starts it will reconnect again

I'm wondering if it's because the code has recognised that (for instance) Jam 3 has occurred, and once Jam 3 is deleted it can't find the data again until Jam 3 "happens" _again_ ?

**Comment by dhmay** [comment] 2023-02-13 00:44
OK, thanks for the test. I think 2 will be easy for me to replicate and fix. I thought I'd fixed 1 already, so that might take some more doing.

**Comment by dhmay** [comment] 2023-02-13 05:01
@bullseye555 I fixed the second issue, with unstarting a jam, and that was actually a really important fix for dealing with the nulling-out of existing data properly. You can test it here:
https://github.com/dhmay/jamstats/actions/runs/4160253120

**Comment by dhmay** [comment] 2023-02-13 05:29
@bullseye555  OK, I'm now handling a new game. It's not very pretty. Basically, the problem was that the server isn't sending everything I expect to see when a new game starts -- roster information, and stuff. So, for a new game, I'm dropping the connection and reconnecting, to get the scoreboard to send all the game data again.

I hope that doesn't come back to bite me in some other weird corner case. But, now, I believe, you can finish a game, start a new one, start adding game data and see it show up! Please verify.
https://github.com/dhmay/jamstats/actions/runs/4160423151

**Closed** 2023-02-13 05:29 UTC
Labels: bug

**Comment by bullseye555** [comment] 2023-02-13 06:40
```Chefs Kiss```

Point 1 confirmed as resolved, it drops the connection (and displays the _just finished_ game summary until the next refresh was due to occur)
![image](https://user-images.githubusercontent.com/28804763/218387803-1426aba7-c8eb-4aa1-a5db-a6c03076175c.png)

Point 2 confirmed as resolved, it does a whole heap of NULLing of the Jam that was removed and the JamStats stays connected to the game in progress the whole time
![image](https://user-images.githubusercontent.com/28804763/218387935-5cc960ab-af77-4ded-afc6-bcc0a7e00fd6.png)

**Comment by dhmay** [comment] 2023-02-14 02:33
lol sorry, @bullseye555 . Those "Nulling out"s were debugging code that I left in there. I removed them... if they bug you you can grab the latest build under "Actions".

I think we're done here! At least for now!

**Comment by bullseye555** [comment] 2023-02-14 03:05
All good, wasn't sure if it was supposed to be there, but it was a good visual evidence that it was doing what it was supposed to be!

Doesn't bother me, so I'll just keep using the current asset until the next release :)
